server:
  port: 8084
  servlet:
    context-path: /api/v1
    #files
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

spring:
  application:
    name: helpmeiud
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  # ORM
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#spring security
security:
  jwt:
    client-service: HelpmeIUD
    password-service:
    scope-read: read
    scope-write: write
    grant-password: password
    grant-refresh: refresh_token
    token-validity-seconds: 3600
    refresh-validity-seconds: 3600