server:
  port: 8084
  servlet:
    context-path: /api/v1
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

spring:
  application:
    name: helpmeiud
  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3307/helpme_iud?createDatabaseIfNotExist=true
    username: root
    password: 1996

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: creyhenao@gmail.com
    password: wvrv uliv fngn dqan
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ORM
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

security:
  jwt:
    client-service: HelpmeIUD
    password-service: 123456
    scope-read: read
    scope-write: write
    grant-password: password
    grant-refresh: refresh_token
    token-validity-seconds: 3600
    refresh-validity-seconds: 3600


